### ISSUE TITLE
Fails after parks

### ISSUE THREAD

**Issue by ubqtous** [92jackson/mainsail-advanced-filament-swap#1]
Using PrusaSlicer, Klipper and Mainsail. Latest version all.

After M600, head parks, I get a popup with unloading filament, I press OK I get the error below and nothing happens. 

05:20:59 PM
Extrude only move too long (-300.000mm vs 200.000mm)
05:20:59 PM
Extrude only move too long (-300.000mm vs 200.000mm)
See the 'max_extrude_only_distance' config option for details
05:20:59 PM
Unloading your filament ...
05:20:59 PM
The hotend's temperature is set to 190.0oC
05:20:42 PM
Heating the hotend to 200oC
05:20:41 PM
Parking the print head in the maintenance position
05:20:41 PM
Your current filament is unloading.

Please wait ...

**Comment by 92jackson** [comment]
Check your printer.cfg for `max_extrude_only_distance`, it looks like you need to increase the value
